### ISSUE TITLE
Please add small demo for API search

### ISSUE THREAD

**Issue by maschu09** [EUDAT-Training/B2SHARE-Training#12]
record search is unfortunately not well documented.

At https://eudat.eu/services/userdoc/b2share-http-rest-api#search-records it only says 

> curl "https://$B2SHARE_HOST/api/records/?q=$QUERY_STRING"

But it says nowhere how this query string looks like.

**Comment by hevp** [comment]
Thanks for reporting.

The documentation has been updated accordingly:
- REST API search: https://eudat.eu/services/userdoc/b2share-http-rest-api#search-records
- Advanced search queries: https://eudat.eu/services/userdoc/b2share-advanced-search
