### ISSUE TITLE
Please add information on paging to the REST API documentation

### ISSUE THREAD

**Issue by maschu09** [EUDAT-Training/B2SHARE-Training#14]
The `records` command returns only ten records by default. You must use pagination to retrieve more records. Output can be controlled with `page`and `size`. For example:

```
${B2SHARE_INSTANCE}/api/records/?size=50&page=2
```
will return the records from number 50 to 99 (if there are at least 100 records posted on this instance).

**Comment by hevp** [comment]
See also: https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/api/02_List_existing_records.md#retrieve-a-list-of-records

**Comment by hevp** [comment]
Thanks for reporting. The documentation is updated: https://eudat.eu/services/userdoc/b2share-http-rest-api
