### ISSUE TITLE
Deposit commit has the wrong URL

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-Training/B2SHARE-Training#4]
In this section: https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/05_Create_new_deposit.md#commit-the-changes, when the deposit is committed by the post request:

```
>>> r = requests.post(url, data=json.dumps(metadata), params=payload, verify=False, headers=headers)
>>> print r
<Response [201]>
```

the `url` retains its previous value, `url = 'https://trng-b2share.eudat.eu/api/deposition/' + depositid + '/files'`, so it ends in `/files`, which is incorrect. 

Solution:
Before this call, the url must be updated to end in `/commit`, like so:
`url = 'https://trng-b2share.eudat.eu/api/deposition/' + depositid + '/commit'`

**Comment by hevp** [comment]
Indeed, is fixed now!
Thanks for noticing.
